/* CRIANDO UM BANCO */
CREATE DATABASE BEBIDAS;

/* CONECTANDO */
USE BEBIDAS;

/* CRIANDO A TABELA */

CREATE TABLE BEBIDAS(
	IDCLIENTE INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	MARCA VARCHAR(20)  NOT NULL,
	TIPO VARCHAR(30),
	EMBALAGEM VARCHAR(15),
	VOLUME INT,
	ALCOOLICA CHAR(3)
);

INSERT INTO BEBIDAS VALUES
('Coca-Cola', 'Coca-Cola', 'Refrigerante', 'Lata', 350, 'Nao');

INSERT INTO BEBIDAS VALUES
('Agua Crystal', 'Coca-Cola', 'Agua', 'Garrafa', 500, 'Nao'),
('Caracu', 'AMBEV', 'Cerveja', 'Lata', 350, 'SIM'),
('Bulleit Bourbon', 'DIAGEO', 'Bourbon', 'Garrafa', 750, 'Sim'),
('Ketel One', 'Diageo', 'Vodka', 'Garrafa', 1000, 'Sim');

SELECT * FROM BEBIDAS;

UPDATE BEBIDAS SET MARCA = 'DIAGEO' WHERE NOME = 'KETEL ONE';

DELETE BEBIDAS WHERE NOME = 'Agua Crystal';

SELECT NOME, MARCA, TIPO, EMBALAGEM, VOLUME AS ML, ALCOOLICA AS ALCOOL FROM BEBIDAS WHERE ALCOOLICA = 'Sim';

SELECT NOME FROM BEBIDAS WHERE NOME LIKE '%One%';

SELECT NOME FROM BEBIDAS WHERE EMBALAGEM = 'Garrafa' AND ALCOOLICA = 'Sim';

SELECT COUNT(NOME) FROM BEBIDAS;

SELECT COUNT(NOME), ALCOOLICA FROM BEBIDAS GROUP BY ALCOOLICA;


/*CRIE UM BANCO DE DADOS PARA CONTROLAR BEBIDAS ALCOÓLICAS/NÃO ALCOÓLICAS
E UTILIZE OS SEGUINTES COMANDOS:

1. UPDATE / DELETE
2. ALIAS
3. WHERE E LIKE
4. OPERADORES LOGICOS
5. COUNT
6. GROUP BY
7. FILTROS DE VALORES NULOS E NÃO NULOS

*/
